### ISSUE TITLE
感觉很多扩展功能和node兼容层的思路有些重复？

### ISSUE THREAD

**Issue by zombieyang** [ialex32x/unity-jsb#11]
很喜欢这个项目的想法。

稍微探讨一些问题
有node兼容层的话，像Websocket、pb之类的功能直接通过npm包就能实现了？
另外就是后续有考虑过同时支持V8和QuickJS两种方式吗，可能某些场景还是希望要有JIT的。

**Comment by ialex32x** [comment]
没有做到实际的node兼容, 只是做了基础的 node_modules 加载逻辑兼容, 以方便直接使用大部分纯 JS 实现的 npm 包.

Websocket 牵涉到 native 代码, 所以没办法直接使用相关的 npm 包, 就简单提供了一个, 还比较初步, 并且后续可能考虑替换成 .NET Websocket backend, 减少第三方依赖. 提供WebSocket 而不是 Socket 主要是方便转换一些来自 H5 的现有代码.
当然, 后续有精力的情况下也会以 Extra 的形式提供 Socket 包装.

pb 用的直接就是 npm protobufjs, 项目里写的只是简单的使用示例, 方便上手.
像 protobufjs, xlsx 等 npm 包, 都是纯 JS 实现的库, 就是直接使用的 (当然, 要在最终环境中使用需要经过webpack打包, 或者直接携带 node_modules 目录)

Extra 目录中的基本属于我个人觉得实际项目中较大概率会使用到的, 但是又可选的功能.

至于可切换使用 V8 backend, 应该是个时间精力问题哈哈

**Comment by ialex32x** [comment]
应该会考虑的, 特别是 V8 的调试非常成熟. JIT的话相对来说对单一平台是有意义的, 但是一旦牵涉到 iOS, 实际代码还是只能以非JIT的性能标准来编写和评估.
