### ISSUE TITLE
为Assembly-CSharp.dll生成xml文档

### ISSUE THREAD

**Issue by littlesome** [ialex32x/unity-jsb#12]
[xmldoc.zip](https://github.com/ialex32x/unity-jsb/files/5402200/xmldoc.zip)

实现了一个为用户代码生成xml文档的bat，供参考，放置在项目根目录即可 （依赖msbuild，需要安装VS）

**Comment by ialex32x** [comment]
很赞👍  
修改了一下 Prefs.cs, 提供了一个 xmlDocDir 配置, 比如 ```Assets/Generated/Docs/```, 在生成 d.ts 的时候会去这个位置寻找对应的文档进行 d.ts 文档注释的生成.

这样配合 Directory.Build.props 指定 DocumentationFile 到 ```Assets/Generated/Docs/``` 就可以搭配起来了.
非常感谢 👏  也欢迎 PR~

**Comment by littlesome** [comment]
最佳方案可能是用Editor\Data\Tools\Roslyn\csc来编译，随Editor编译C#代码一同生成xml
目前没找到优雅的办法做这个事情，
尝试过通过csc.rsp来指定/doc，但这样只能指定一个输出文件名，有多个Assembly的时候xml会覆盖，难受
