### ISSUE TITLE
.NET 4.0编译失败

### ISSUE THREAD

**Issue by liesauer** [ialex32x/unity-jsb#23]
![image](https://user-images.githubusercontent.com/8676741/114292500-73607900-9ac1-11eb-9235-58203dd6f82c.png)
如图，`MethodImplOptions.AggressiveInlining` 只有.NET 4.5+才有，能否兼容到.NET 4.0？

**Comment by liesauer** [comment]
我是做游戏Mod的，受限于游戏本身框架限制，没办法升级到.NET 4.5，目前来说，.NET 3.5和.NET 4.0的游戏还是很多的，希望能兼容支持！

**Comment by ialex32x** [comment]
嗯，这个可以去掉的，我去掉它。

**Comment by liesauer** [comment]
对了，其实还有好多其他的，vs没全提示出来，这个好兼容吗
![image](https://user-images.githubusercontent.com/8676741/114293439-8dea2080-9ac8-11eb-8cb5-680fb88f165d.png)

**Comment by ialex32x** [comment]
好的，会一并检查处理一下

**Comment by liesauer** [comment]
好的，感谢！

**Comment by ialex32x** [comment]
客气，是在纯.NET环境下吗？

**Comment by liesauer** [comment]
mono

**Comment by ialex32x** [comment]
可否给一下具体使用环境，版本信息等

**Comment by liesauer** [comment]
mono 2.0.50727.1433

**Comment by ialex32x** [comment]
编译的问题改好了，需要定义个条件编译 JSB_COMPATIBLE。只是编译通过了，实际运行还是不行的，现在的逻辑流程只能在引擎里运行。会继续修改，以便在 .net 环境运行（通过反射）。
这先 close 啦。
