### ISSUE TITLE
How to add to existing project?

### ISSUE THREAD

**Issue by jeremywho** [ialex32x/unity-jsb#35]
Hi!

I'm wondering how I can add this to an existing project?
It's not clear to me exactly what should be added and what is example code.

**Comment by ialex32x** [comment]
Hi jeremywho, just copy the ```Assets/jsb``` directory to your project, and you could remove ```Assets/jsb/Extra``` directory (or any subdir in it) if you don't need these features.
Then, write a startup script like ```Sample.cs``` to create the script engine and run its mainloop.

**Comment by jeremywho** [comment]
Thank-you!
