### ISSUE TITLE
duktape => jsb

### ISSUE THREAD

**Issue by HAI-SHAN** [ialex32x/unity-jsb#36]
您好，我使用了咱们duktape模块做unity内容的热更新
有时崩溃后只有内存指针的堆栈信息，无法定位崩溃的位置，想请问一下jsb在这块是否有更好的处理方式？
![image](https://user-images.githubusercontent.com/59592050/125600001-d0ac5185-c587-4786-9808-de56c16b88ae.png)

另外，如果从duktape转换到jsb，是否可以不改变原有js代码进行切换？
😲

**Comment by ialex32x** [comment]
这个需要通过符号表再分析具体情况. 
脚本层面对导出类型的组织方式不一样, unity-duktape 直接赋值到 js global 中了, unity-jsb 处理成 js module 了.

**Comment by HAI-SHAN** [comment]
明白了，thank you 🤞

**Comment by HAI-SHAN** [comment]
em,,,,,liangjie，我在android上可以处理这个问题了，不过发现ios碰到的crash问题好像不太一样，像这类的崩溃感觉无法定位问题，不知道你对这个有没有研究？我在使用中感觉一些崩溃很难定位到具体的地方，比如在编辑时报错只显示代码行数，具体的文件名显示为空。想听听你的意见，是否有从duktape切换到jsb会好一点 👀
![](mailmaster://webui/mailvpart/0/-1/97B1ACA3-38A5-4A2A-AEC5-98F99BB72C52.png)

**Comment by ialex32x** [comment]
抱歉带来不便, 还没有经过深入应用, 肯定存在一些问题, 不过具体分析还是得依靠调试信息, 得编译DEBUG版本或带上符号表.
目前的时间精力只够在 jsb 上继续改进, jsb 在异常处理上更健全一点, 另外修过几个delegate生命周期相关的问题, 你碰到的崩溃是否跟delegate有关? 可以详细沟通一下, qq 411982213
