### ISSUE TITLE
Possible to generate bindings/typings for custom .dlls?

### ISSUE THREAD

**Issue by jeremywho** [ialex32x/unity-jsb#37]
I have a custom dll that I'd like to use in typescript. Is it possible to generate bindings/types for that?

One other thing that is not clear to me is how to use c#<->typescript bindings. Do I just add a `@ScriptType()` decorator to my typescript classes to make them available in c#?

**Comment by ialex32x** [comment]
If it's a managed dll, you could directly expose all types in it. This process looks like:
```cs
using System.Reflection;

namespace Example.Editor
{
    using QuickJS.Binding;

    public class CustomBinding : AbstractBindingProcess
    {
        public override string GetBindingProcessName()
        {
            return "dotnetcore";
        }

        public override void OnPreExporting(BindingManager bindingManager)
        {
            bindingManager.AddExportedType(typeof(System.Math));
        }
        
        public override void OnPostExporting(BindingManager bindingManager)
        {
            bindingManager.ExportTypesInAssembly(typeof(System.Threading.Thread).Assembly, true);
            bindingManager.ExportTypesInAssembly(typeof(System.Console).Assembly, true);
        }
    }
}
```

Or if it's a native dll/so, there is no way to achive it at the moment, you need to write some glue code.

**Comment by ialex32x** [comment]
For C# Types, they could be exposed to typescript by adding ```[QuickJS.JSType]``` attribute or exporting by ```bindingManager.AddExportedType``` in CustomBinding process. 

There is no easy way to access typescript classes reversely in C#.

The ```@ScriptType()``` decorator is used to mark the MonoBehaviour classes implemented in typescript, then The editor will be able to list these classes in an editor search box. (If you add ```JSBehaviour``` or ```JSBehaviourFull``` component to an GameObject, you can directly select a typescript class from a search box)
There is an example about this feature, you could read ```example_monobehaviour.ts``` and ```my_class_inspector.ts``` for details.
It's very similar to what you can do in C#.
