### ISSUE TITLE
Example calling JS from C#

### ISSUE THREAD

**Issue by FreakTheMighty** [ialex32x/unity-jsb#41]
Do you have any examples of calling a JS function with an argument from C#? I’d like to call something like a “main” method in a JavaScript method and pass in some context form c#. Any pointers would be much appreciated.

**Comment by ialex32x** [comment]
haven't supplied an easy method to archive it without delegate yet. there are some implemented but not so smooth ways:
1. use EvalMain/EvalSource
```cs 
var fn = runtime.EvalSource<ScriptFunction>(...);
fn.Invoke<RetrnType>(...);
```

2. use native api like in Assets/jsb/Source/Unity/Editor/JSAssetPostprocessor.cs
3. write a C# function to process
```cs
void Run(ScriptFunction fn)
{
    fn.Invoke<...>(...);
}
```
```ts
csharp.Run(function () {...}); // the function will be automatically convert into ScriptFunction in C#
```

I'll improve this part in the future.

**Comment by FreakTheMighty** [comment]
Thanks for the help @ialex32x . For others looking for a similar pattern here's what worked. I got a bit confused about the context that `EvalSource` was running in. Using `require` inside of the `EvalSource` gives me exactly what I'd like.


```js
function run(core) {
    console.log(core);
}
exports.run = run;
```
```c#
        runtime.EvalMain(entryFileName);
        var func = runtime.GetMainContext().EvalSource<ScriptFunction>("require('main').run", "eval");
        func.Invoke(new {});
```
