### ISSUE TITLE
Is it possible to sandbox a js script?

### ISSUE THREAD

**Issue by FreakTheMighty** [ialex32x/unity-jsb#6]
Is it possible to limit js access to specific C# classes and functions?

**Comment by ialex32x** [comment]
At present, there is no direct support for this feature, but you can create runtime for every js sandbox script (just like the worker). I will continue to think about it, if any better solution exists.

**Comment by FreakTheMighty** [comment]
Thanks @ialex32x ! Can you elaborate a bit on your answer? Perhaps you can link to the worker example to which you’re referring.

**Comment by ialex32x** [comment]
Assets/jsb/Source/JSWorker.cs
Assets/Examples/Scripts/src/example_worker.ts

It's not for sandboxing environment, but for basic Worker API compatible (and this feature still developing in progress).
But It's similar, because it uses a sperate runtime for a js script.

**Comment by ialex32x** [comment]
You can create a ScriptRuntime by ```ScriptEngine.CreateRuntime()```. I'll add an example for it.

**Comment by FreakTheMighty** [comment]
This project is **REALLY** cool! My long term interest is in using this to enable runtime scripting where only some hand crafted API's are exposed. I'm still trying to wrap my head around the examples.

* What happens when we "generate bindings"? Is this an automated way of exposing Unity APIs to to a scripting runtime?
* What is the ducktape.json? I see the UI, but I can't seem to find the actual file. Can this be used to limit which assemblies are exposed to the scripting runtime?
* I see that I can execute code at runtime using the `JS Console`. Do you use this project for runtime scripting, or do you use this project to develop Unity projects in TypeScript and ship with the scripts embedded?

**Comment by ialex32x** [comment]
Thank you, I'm happy if this project helps.
* Yes, "generate bindings" is an automated way of exposing class/functions writen in C#, it generate the glue code (with some techniques to avoid GC Alloc of valuetypes, Vectro3/Quaternion etc.).
* Please ignore the duktape.json file, it's a legacy file from [duktape-unity](https://github.com/ialex32x/duktape-unity), I just rewrite the whole project, replace duktape with quickjs.
* ```JS Console``` is an experimental feature, for the ability to run js script in UnityEditor runtime eventually. I will use unity-jsb to develop Unity project in Typescript, with scripts embedded or as downloadable contents (if it's allowed by the target platform, it depends on you how the scripts load implemented by ```IFileSystem```).
