### ISSUE TITLE
Webpack error when running npm run-script dev or watch

### ISSUE THREAD

**Issue by filharvey** [ialex32x/unity-jsb#62]
getting an error when running webpack, to compile changes.

```
LOG from copy-webpack-plugin
<e> unable to locate 'E:\OtherCode\unity-jsb\Scripts\dist' at 'E:\OtherCode\unity-jsb\Scripts\dist\**\*'
+ 32 hidden lines

ERROR in unable to locate 'E:\OtherCode\unity-jsb\Scripts\dist' at 'E:\OtherCode\unity-jsb\Scripts\dist\**\*'
```

I'm on windows, and have done npm install.

**Comment by ialex32x** [comment]
webpack is not fully support (especially the webpack-dev-server existed for HMR but not supported at present). 
```npm run build/watch``` is minimally supported. (If webpack watch reports the aforementioned error, is it possible  ```tsc -w``` is already running?)

**Comment by filharvey** [comment]
Thanks, I just installed tsc and ran tsc -w and all works fine, I can tweak the js files and see the changes in unity.
