### ISSUE TITLE
Generate Bindings And Type Definition error

### ISSUE THREAD

**Issue by iraymondking** [ialex32x/unity-jsb#64]
unity 2019.4.18f1,windows platform

clone the project, and click Generate Bindings And Type Definition.
get the error blelow:

Assets\Generated\Windows\_QuickJSDelegates.cs(1722,19): error CS0116: A namespace cannot directly contain members such as fields or methods
Assets\Generated\Windows\_QuickJSDelegates.cs(1722,42): error CS1022: Type or namespace definition, or end-of-file expected
Assets\Generated\Windows\_QuickJSDelegates.cs(1723,19): error CS0116: A namespace cannot directly contain members such as fields or methods
......

**Comment by ialex32x** [comment]
The issue causes compilation error has been fixed. There are other issues that remain in the codegen, I'll fix them later. Such as support of high dimensions array.
