### ISSUE TITLE
example_websocket 'WebSocket' is not defined

### ISSUE THREAD

**Issue by TheGJ** [ialex32x/unity-jsb#71]
Hello,

I tried to open the unity example project with the sample scene configured to load the websocket example and I get :

[native] failed to load module: example_websocket 'WebSocket' is not defined

Any idea? Thanks a lot!

**Comment by ialex32x** [comment]
Hi TheGJ, Thank you for reporting this issue, it's a trivial bug caused by the refactoring of register.CreateClass(), it's separated into CreateClass() and CreateGlobalClass() with different purposes. It's fixed in the last commit. Thanks again.
