### ISSUE TITLE
UNITY_EDITOR conflicting with binding

### ISSUE THREAD

**Issue by FreakTheMighty** [ialex32x/unity-jsb#96]
With jsb.Editor.UnityBinding enabled, the generated bindings produce

```c#
        public static ClassDecl Bind(TypeRegister register)
        {
            var cls = register.CreateClass("ScriptableObject", typeof(UnityEngine.ScriptableObject), QuickJS.Binding.CommonFix.CrossBindConstructor);
            cls.AddMethod(true, "CreateInstance", QuickJS.Unity.ScriptableObjectFix.BindStatic_CreateInstance);
            return cls;
        }
```

However, this method `ScriptableObjectFix.BindStatic_CreateInstance`, is wrapped inside of a `#if UNITY_EDITOR`, so it fails on build.

Am I missing something? Is there a way  to indicate that the bindings for editor only methods should be skipped or wrapped in their own directives?

**Comment by ialex32x** [comment]
`ScriptableObjectFix.BindStatic_CreateInstance` should be available even if UNITY_EDITOR is not defined.  @FreakTheMighty Thanks a lot.
